### PR TITLE
Add "class-name": true

### PR DESCRIPTION
**Pull request by testerez**
https://palantir.github.io/tslint/rules/class-name/

### CODE REVIEW

**Comment by progre** [comment]
Please link a new rule with airbnb rule.

**Comment by testerez** [comment]
Here it is: https://github.com/airbnb/javascript#naming--PascalCase

**Comment by progre** [comment]
OK.
Please add a rule number (23.3) with comment, and sort it.

**Comment by testerez** [comment]
I added the version but I'm not sure what you mean by sorting it. The rest of the rules look like in random order.

**Comment by progre** [comment]
thanks mate!

**Pull request merged**
